'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace Live.Search
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="MSNSearchPortBinding", [Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class MSNSearchService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SearchOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://soap.search.live.com:80/webservices.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SearchCompleted As SearchCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.microsoft.com/MSNSearch/2005/09/fex/Search", RequestNamespace:="http://schemas.microsoft.com/MSNSearch/2005/09/fex", ResponseNamespace:="http://schemas.microsoft.com/MSNSearch/2005/09/fex", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Search(ByVal Request As SearchRequest) As <System.Xml.Serialization.XmlElementAttribute("Response")> SearchResponse
            Dim results() As Object = Me.Invoke("Search", New Object() {Request})
            Return CType(results(0),SearchResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SearchAsync(ByVal Request As SearchRequest)
            Me.SearchAsync(Request, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SearchAsync(ByVal Request As SearchRequest, ByVal userState As Object)
            If (Me.SearchOperationCompleted Is Nothing) Then
                Me.SearchOperationCompleted = AddressOf Me.OnSearchOperationCompleted
            End If
            Me.InvokeAsync("Search", New Object() {Request}, Me.SearchOperationCompleted, userState)
        End Sub
        
        Private Sub OnSearchOperationCompleted(ByVal arg As Object)
            If (Not (Me.SearchCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SearchCompleted(Me, New SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class SearchRequest
        
        Private appIDField As String
        
        Private queryField As String
        
        Private cultureInfoField As String
        
        Private safeSearchField As SafeSearchOptions
        
        Private flagsField As SearchFlags
        
        Private locationField As Location
        
        Private requestsField() As SourceRequest
        
        Public Sub New()
            MyBase.New
            Me.safeSearchField = SafeSearchOptions.Moderate
            Me.flagsField = SearchFlags.None
        End Sub
        
        '''<remarks/>
        Public Property AppID() As String
            Get
                Return Me.appIDField
            End Get
            Set
                Me.appIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Query() As String
            Get
                Return Me.queryField
            End Get
            Set
                Me.queryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CultureInfo() As String
            Get
                Return Me.cultureInfoField
            End Get
            Set
                Me.cultureInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SafeSearch() As SafeSearchOptions
            Get
                Return Me.safeSearchField
            End Get
            Set
                Me.safeSearchField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Flags() As SearchFlags
            Get
                Return Me.flagsField
            End Get
            Set
                Me.flagsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Location() As Location
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Requests() As SourceRequest()
            Get
                Return Me.requestsField
            End Get
            Set
                Me.requestsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Public Enum SafeSearchOptions
        
        '''<remarks/>
        Moderate
        
        '''<remarks/>
        Strict
        
        '''<remarks/>
        Off
    End Enum
    
    '''<remarks/>
    <System.FlagsAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Public Enum SearchFlags
        
        '''<remarks/>
        None = 1
        
        '''<remarks/>
        MarkQueryWords = 2
        
        '''<remarks/>
        DisableSpellCorrectForSpecialWords = 4
        
        '''<remarks/>
        DisableHostCollapsing = 8
        
        '''<remarks/>
        DisableLocationDetection = 16
        
        '''<remarks/>
        DisableWebQueryAlteration = 32
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class Location
        
        Private latitudeField As Double
        
        Private longitudeField As Double
        
        Private radiusField As Double
        
        Public Sub New()
            MyBase.New
            Me.radiusField = 5R
        End Sub
        
        '''<remarks/>
        Public Property Latitude() As Double
            Get
                Return Me.latitudeField
            End Get
            Set
                Me.latitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Longitude() As Double
            Get
                Return Me.longitudeField
            End Get
            Set
                Me.longitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.ComponentModel.DefaultValueAttribute(5R)>  _
        Public Property Radius() As Double
            Get
                Return Me.radiusField
            End Get
            Set
                Me.radiusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class MotionThumbnail
        
        Private uRLField As String
        
        Private formatField As String
        
        Private runTimeField As Integer
        
        Private runTimeFieldSpecified As Boolean
        
        Private widthField As Integer
        
        Private widthFieldSpecified As Boolean
        
        Private heightField As Integer
        
        Private heightFieldSpecified As Boolean
        
        Private fileSizeField As Integer
        
        Private fileSizeFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property URL() As String
            Get
                Return Me.uRLField
            End Get
            Set
                Me.uRLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Format() As String
            Get
                Return Me.formatField
            End Get
            Set
                Me.formatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RunTime() As Integer
            Get
                Return Me.runTimeField
            End Get
            Set
                Me.runTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RunTimeSpecified() As Boolean
            Get
                Return Me.runTimeFieldSpecified
            End Get
            Set
                Me.runTimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Width() As Integer
            Get
                Return Me.widthField
            End Get
            Set
                Me.widthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property WidthSpecified() As Boolean
            Get
                Return Me.widthFieldSpecified
            End Get
            Set
                Me.widthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Height() As Integer
            Get
                Return Me.heightField
            End Get
            Set
                Me.heightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HeightSpecified() As Boolean
            Get
                Return Me.heightFieldSpecified
            End Get
            Set
                Me.heightFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FileSize() As Integer
            Get
                Return Me.fileSizeField
            End Get
            Set
                Me.fileSizeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FileSizeSpecified() As Boolean
            Get
                Return Me.fileSizeFieldSpecified
            End Get
            Set
                Me.fileSizeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class StaticThumbnail
        
        Private uRLField As String
        
        Private formatField As String
        
        Private widthField As Integer
        
        Private widthFieldSpecified As Boolean
        
        Private heightField As Integer
        
        Private heightFieldSpecified As Boolean
        
        Private fileSizeField As Integer
        
        Private fileSizeFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property URL() As String
            Get
                Return Me.uRLField
            End Get
            Set
                Me.uRLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Format() As String
            Get
                Return Me.formatField
            End Get
            Set
                Me.formatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Width() As Integer
            Get
                Return Me.widthField
            End Get
            Set
                Me.widthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property WidthSpecified() As Boolean
            Get
                Return Me.widthFieldSpecified
            End Get
            Set
                Me.widthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Height() As Integer
            Get
                Return Me.heightField
            End Get
            Set
                Me.heightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HeightSpecified() As Boolean
            Get
                Return Me.heightFieldSpecified
            End Get
            Set
                Me.heightFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FileSize() As Integer
            Get
                Return Me.fileSizeField
            End Get
            Set
                Me.fileSizeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FileSizeSpecified() As Boolean
            Get
                Return Me.fileSizeFieldSpecified
            End Get
            Set
                Me.fileSizeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class Video
        
        Private playUrlField As String
        
        Private sourceTitleField As String
        
        Private formatField As String
        
        Private runTimeField As Integer
        
        Private runTimeFieldSpecified As Boolean
        
        Private widthField As Integer
        
        Private widthFieldSpecified As Boolean
        
        Private heightField As Integer
        
        Private heightFieldSpecified As Boolean
        
        Private fileSizeField As Integer
        
        Private fileSizeFieldSpecified As Boolean
        
        Private staticThumbnailField As StaticThumbnail
        
        Private motionThumbnailField As MotionThumbnail
        
        '''<remarks/>
        Public Property PlayUrl() As String
            Get
                Return Me.playUrlField
            End Get
            Set
                Me.playUrlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SourceTitle() As String
            Get
                Return Me.sourceTitleField
            End Get
            Set
                Me.sourceTitleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Format() As String
            Get
                Return Me.formatField
            End Get
            Set
                Me.formatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RunTime() As Integer
            Get
                Return Me.runTimeField
            End Get
            Set
                Me.runTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property RunTimeSpecified() As Boolean
            Get
                Return Me.runTimeFieldSpecified
            End Get
            Set
                Me.runTimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Width() As Integer
            Get
                Return Me.widthField
            End Get
            Set
                Me.widthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property WidthSpecified() As Boolean
            Get
                Return Me.widthFieldSpecified
            End Get
            Set
                Me.widthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Height() As Integer
            Get
                Return Me.heightField
            End Get
            Set
                Me.heightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property HeightSpecified() As Boolean
            Get
                Return Me.heightFieldSpecified
            End Get
            Set
                Me.heightFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FileSize() As Integer
            Get
                Return Me.fileSizeField
            End Get
            Set
                Me.fileSizeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FileSizeSpecified() As Boolean
            Get
                Return Me.fileSizeFieldSpecified
            End Get
            Set
                Me.fileSizeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StaticThumbnail() As StaticThumbnail
            Get
                Return Me.staticThumbnailField
            End Get
            Set
                Me.staticThumbnailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MotionThumbnail() As MotionThumbnail
            Get
                Return Me.motionThumbnailField
            End Get
            Set
                Me.motionThumbnailField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class Image
        
        Private imageURLField As String
        
        Private imageWidthField As Integer
        
        Private imageWidthFieldSpecified As Boolean
        
        Private imageHeightField As Integer
        
        Private imageHeightFieldSpecified As Boolean
        
        Private imageFileSizeField As Integer
        
        Private imageFileSizeFieldSpecified As Boolean
        
        Private thumbnailURLField As String
        
        Private thumbnailWidthField As Integer
        
        Private thumbnailWidthFieldSpecified As Boolean
        
        Private thumbnailHeightField As Integer
        
        Private thumbnailHeightFieldSpecified As Boolean
        
        Private thumbnailFileSizeField As Integer
        
        Private thumbnailFileSizeFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property ImageURL() As String
            Get
                Return Me.imageURLField
            End Get
            Set
                Me.imageURLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImageWidth() As Integer
            Get
                Return Me.imageWidthField
            End Get
            Set
                Me.imageWidthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ImageWidthSpecified() As Boolean
            Get
                Return Me.imageWidthFieldSpecified
            End Get
            Set
                Me.imageWidthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImageHeight() As Integer
            Get
                Return Me.imageHeightField
            End Get
            Set
                Me.imageHeightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ImageHeightSpecified() As Boolean
            Get
                Return Me.imageHeightFieldSpecified
            End Get
            Set
                Me.imageHeightFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImageFileSize() As Integer
            Get
                Return Me.imageFileSizeField
            End Get
            Set
                Me.imageFileSizeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ImageFileSizeSpecified() As Boolean
            Get
                Return Me.imageFileSizeFieldSpecified
            End Get
            Set
                Me.imageFileSizeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThumbnailURL() As String
            Get
                Return Me.thumbnailURLField
            End Get
            Set
                Me.thumbnailURLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThumbnailWidth() As Integer
            Get
                Return Me.thumbnailWidthField
            End Get
            Set
                Me.thumbnailWidthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ThumbnailWidthSpecified() As Boolean
            Get
                Return Me.thumbnailWidthFieldSpecified
            End Get
            Set
                Me.thumbnailWidthFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThumbnailHeight() As Integer
            Get
                Return Me.thumbnailHeightField
            End Get
            Set
                Me.thumbnailHeightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ThumbnailHeightSpecified() As Boolean
            Get
                Return Me.thumbnailHeightFieldSpecified
            End Get
            Set
                Me.thumbnailHeightFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ThumbnailFileSize() As Integer
            Get
                Return Me.thumbnailFileSizeField
            End Get
            Set
                Me.thumbnailFileSizeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ThumbnailFileSizeSpecified() As Boolean
            Get
                Return Me.thumbnailFileSizeFieldSpecified
            End Get
            Set
                Me.thumbnailFileSizeFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class SearchTag
        
        Private nameField As String
        
        Private valueField As String
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class Address
        
        Private addressLineField As String
        
        Private primaryCityField As String
        
        Private secondaryCityField As String
        
        Private subdivisionField As String
        
        Private postalCodeField As String
        
        Private countryRegionField As String
        
        Private formattedAddressField As String
        
        '''<remarks/>
        Public Property AddressLine() As String
            Get
                Return Me.addressLineField
            End Get
            Set
                Me.addressLineField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PrimaryCity() As String
            Get
                Return Me.primaryCityField
            End Get
            Set
                Me.primaryCityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SecondaryCity() As String
            Get
                Return Me.secondaryCityField
            End Get
            Set
                Me.secondaryCityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Subdivision() As String
            Get
                Return Me.subdivisionField
            End Get
            Set
                Me.subdivisionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PostalCode() As String
            Get
                Return Me.postalCodeField
            End Get
            Set
                Me.postalCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CountryRegion() As String
            Get
                Return Me.countryRegionField
            End Get
            Set
                Me.countryRegionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FormattedAddress() As String
            Get
                Return Me.formattedAddressField
            End Get
            Set
                Me.formattedAddressField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class DateTime
        
        Private yearField As Integer
        
        Private monthField As Integer
        
        Private dayField As Integer
        
        Private hourField As Integer
        
        Private minuteField As Integer
        
        Private secondField As Integer
        
        '''<remarks/>
        Public Property Year() As Integer
            Get
                Return Me.yearField
            End Get
            Set
                Me.yearField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Month() As Integer
            Get
                Return Me.monthField
            End Get
            Set
                Me.monthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Day() As Integer
            Get
                Return Me.dayField
            End Get
            Set
                Me.dayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Hour() As Integer
            Get
                Return Me.hourField
            End Get
            Set
                Me.hourField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Minute() As Integer
            Get
                Return Me.minuteField
            End Get
            Set
                Me.minuteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Second() As Integer
            Get
                Return Me.secondField
            End Get
            Set
                Me.secondField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class Result
        
        Private titleField As String
        
        Private descriptionField As String
        
        Private urlField As String
        
        Private displayUrlField As String
        
        Private cacheUrlField As String
        
        Private sourceField As String
        
        Private searchTagsField As String
        
        Private phoneField As String
        
        Private dateTimeField As DateTime
        
        Private addressField As Address
        
        Private locationField As Location
        
        Private searchTagsArrayField() As SearchTag
        
        Private summaryField As String
        
        Private resultTypeField As String
        
        Private imageField As Image
        
        Private videoField As Video
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayUrl() As String
            Get
                Return Me.displayUrlField
            End Get
            Set
                Me.displayUrlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CacheUrl() As String
            Get
                Return Me.cacheUrlField
            End Get
            Set
                Me.cacheUrlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SearchTags() As String
            Get
                Return Me.searchTagsField
            End Get
            Set
                Me.searchTagsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Phone() As String
            Get
                Return Me.phoneField
            End Get
            Set
                Me.phoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateTime() As DateTime
            Get
                Return Me.dateTimeField
            End Get
            Set
                Me.dateTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Address() As Address
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Location() As Location
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property SearchTagsArray() As SearchTag()
            Get
                Return Me.searchTagsArrayField
            End Get
            Set
                Me.searchTagsArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Summary() As String
            Get
                Return Me.summaryField
            End Get
            Set
                Me.summaryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResultType() As String
            Get
                Return Me.resultTypeField
            End Get
            Set
                Me.resultTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Image() As Image
            Get
                Return Me.imageField
            End Get
            Set
                Me.imageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Video() As Video
            Get
                Return Me.videoField
            End Get
            Set
                Me.videoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class SourceResponse
        
        Private sourceField As SourceType
        
        Private offsetField As Integer
        
        Private totalField As Integer
        
        Private recourseQueryField As String
        
        Private resultsField() As Result
        
        '''<remarks/>
        Public Property Source() As SourceType
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Offset() As Integer
            Get
                Return Me.offsetField
            End Get
            Set
                Me.offsetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total() As Integer
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RecourseQuery() As String
            Get
                Return Me.recourseQueryField
            End Get
            Set
                Me.recourseQueryField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Results() As Result()
            Get
                Return Me.resultsField
            End Get
            Set
                Me.resultsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Public Enum SourceType
        
        '''<remarks/>
        Web
        
        '''<remarks/>
        News
        
        '''<remarks/>
        Ads
        
        '''<remarks/>
        InlineAnswers
        
        '''<remarks/>
        PhoneBook
        
        '''<remarks/>
        WordBreaker
        
        '''<remarks/>
        Spelling
        
        '''<remarks/>
        QueryLocation
        
        '''<remarks/>
        Image
        
        '''<remarks/>
        Video
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class SearchResponse
        
        Private responsesField() As SourceResponse
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Responses() As SourceResponse()
            Get
                Return Me.responsesField
            End Get
            Set
                Me.responsesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Partial Public Class SourceRequest
        
        Private sourceField As SourceType
        
        Private offsetField As Integer
        
        Private countField As Integer
        
        Private fileTypeField As String
        
        Private sortByField As SortByType
        
        Private resultFieldsField As ResultFieldMask
        
        Private searchTagFiltersField() As String
        
        Public Sub New()
            MyBase.New
            Me.sourceField = SourceType.Web
            Me.offsetField = 0
            Me.countField = 10
            Me.sortByField = SortByType.[Default]
            Me.resultFieldsField = ((ResultFieldMask.Title Or ResultFieldMask.Description)  _
                        Or ResultFieldMask.Url)
        End Sub
        
        '''<remarks/>
        Public Property Source() As SourceType
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Offset() As Integer
            Get
                Return Me.offsetField
            End Get
            Set
                Me.offsetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Count() As Integer
            Get
                Return Me.countField
            End Get
            Set
                Me.countField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FileType() As String
            Get
                Return Me.fileTypeField
            End Get
            Set
                Me.fileTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.ComponentModel.DefaultValueAttribute(SortByType.[Default])>  _
        Public Property SortBy() As SortByType
            Get
                Return Me.sortByField
            End Get
            Set
                Me.sortByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ResultFields() As ResultFieldMask
            Get
                Return Me.resultFieldsField
            End Get
            Set
                Me.resultFieldsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property SearchTagFilters() As String()
            Get
                Return Me.searchTagFiltersField
            End Get
            Set
                Me.searchTagFiltersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.FlagsAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Public Enum SortByType
        
        '''<remarks/>
        [Default] = 1
        
        '''<remarks/>
        Relevance = 2
        
        '''<remarks/>
        Distance = 4
    End Enum
    
    '''<remarks/>
    <System.FlagsAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/MSNSearch/2005/09/fex")>  _
    Public Enum ResultFieldMask
        
        '''<remarks/>
        All = 1
        
        '''<remarks/>
        Title = 2
        
        '''<remarks/>
        Description = 4
        
        '''<remarks/>
        Url = 8
        
        '''<remarks/>
        DisplayUrl = 16
        
        '''<remarks/>
        CacheUrl = 32
        
        '''<remarks/>
        Source = 64
        
        '''<remarks/>
        SearchTags = 128
        
        '''<remarks/>
        Phone = 256
        
        '''<remarks/>
        DateTime = 512
        
        '''<remarks/>
        Address = 1024
        
        '''<remarks/>
        Location = 2048
        
        '''<remarks/>
        SearchTagsArray = 4096
        
        '''<remarks/>
        Summary = 8192
        
        '''<remarks/>
        ResultType = 16384
        
        '''<remarks/>
        Image = 32768
        
        '''<remarks/>
        Video = 65536
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub SearchCompletedEventHandler(ByVal sender As Object, ByVal e As SearchCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SearchCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SearchResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SearchResponse)
            End Get
        End Property
    End Class
End Namespace
